version: '3'

services:
  node:
    build:
      context: ./
      target: dev
    volumes:
      - ./:/app
    command: npm run start
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - db